### ISSUE TITLE
Achieve compatibility with Meteor examples

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#2414]
### What should be done?

TBD

**Comment by b1ron** [comment]
Sounds good!

**Comment by b1ron** [comment]
We are basically compatible with the [blaze tutorial](https://github.com/meteor/blaze-tutorial) if we exclude #2448. This tutorial is what https://github.com/wreiske/meteor-ferretdb is pulling from.

To test it I ignored sparse indexes and it worked. 

It doesn't seem to be using the `$` projection operator to refresh user tokens, so I don't get logged out of the session. But I still see the below error:

```
➜  step13 git:(master) ✗ MONGO_URL=mongodb://localhost:27017/ meteor
[[[[[ ~/workdir/blaze-tutorial/src/simple-todos/step13 ]]]]]

=> Started proxy.                             
=> Started HMR server.                        
=> Meteor 2.11.0 is available. Check the changelog https://docs.meteor.com/changelog.html and update this project with 'meteor update'.
=> Started your app.

=> App running at: http://localhost:3000/
I20230501-20:58:48.854(2)? Exception while invoking method 'login' TypeError: Cannot read property 'resume' of undefined
I20230501-20:58:48.881(2)?     at MethodInvocation.defaultResumeLoginHandler (packages/accounts-base/accounts_server.js:1577:29)
I20230501-20:58:48.881(2)?     at MethodInvocation.<anonymous> (packages/accounts-base/accounts_server.js:1532:38)
I20230501-20:58:48.882(2)?     at packages/accounts-base/accounts_server.js:594:31
I20230501-20:58:48.882(2)?     at tryLoginMethod (packages/accounts-base/accounts_server.js:1518:14)
I20230501-20:58:48.882(2)?     at AccountsServer._runLoginHandlers (packages/accounts-base/accounts_server.js:592:22)
I20230501-20:58:48.882(2)?     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:652:31)
I20230501-20:58:48.882(2)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1885:12)
I20230501-20:58:48.882(2)?     at packages/ddp-server/livedata_server.js:769:19
I20230501-20:58:48.882(2)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
I20230501-20:58:48.883(2)?     at packages/ddp-server/livedata_server.js:767:46
I20230501-20:58:48.883(2)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
I20230501-20:58:48.883(2)?     at packages/ddp-server/livedata_server.js:765:46
I20230501-20:58:48.883(2)?     at new Promise (<anonymous>)
I20230501-20:58:48.883(2)?     at Session.method (packages/ddp-server/livedata_server.js:739:23)
I20230501-20:58:48.885(2)?     at packages/ddp-server/livedata_server.js:603:43

```

**Comment by mitar** [comment]
If you really want to stress test out Meteor and MongoDB integration, I suggest using my old [meteor-peerdb](https://github.com/peerlibrary/meteor-peerdb/blob/master/tests.coffee) test suite. It has managed to find issues with Meteor implementation itself. :-)

**Comment by b1ron** [comment]
thanks @mitar, we will check it out!

**Comment by AlekSi** [comment]
We just released a new version with OpLog tailing support, which was a major blocker for supporting Meteor apps: https://github.com/FerretDB/FerretDB/releases/tag/v1.18.0
