### ISSUE TITLE
`findAndModify` should allow empty `fields`

### ISSUE THREAD

**Issue by ecerroni** [FerretDB/FerretDB#3797]
### FerretDB version

Hey, first of all the idea behind FerretDB is awesome.

I've been trying to swap mongodb with ferretDB for one of my projects, but I am getting an error related to findAndModify.

I am connecting to mongo using mongoose.

```
[MONGO][INFO]:  User Connection Established
[MONGO][INFO]:  User Connected to db
[MONGO][INFO]:  Relationship Connection Established
[MONGO][INFO]:  Relationship Connected to db
(node:29600) UnhandledPromiseRejectionWarning: Error: findAndModify: support for field "fields" with value &{map[] [] false 0} is not implemented yet
    at MongoServerError.<anonymous> (/home/rico/DEV/ME/boilerplates/mercurius-connector-kit-mongoose/backend/node_modules/@babel/node/node_modules/core-js/internals/wrap-error-constructor-with-cause.js:37:62)
    at new Error (/home/rico/DEV/ME/boilerplates/mercurius-connector-kit-mongoose/backend/node_modules/@babel/node/node_modules/core-js/modules/es.error.cause.js:28:43)
    at new MongoError (/home/rico/DEV/ME/boilerplates/mercurius-connector-kit-mongoose/backend/node_modules/mongodb/src/error.ts:93:7)
    at new MongoServerError (/home/rico/DEV/ME/boilerplates/mercurius-connector-kit-mongoose/backend/node_modules/mongodb/src/error.ts:147:5)
    at MessageStream.messageHandler (/home/rico/DEV/ME/boilerplates/mercurius-connector-kit-mongoose/backend/node_modules/mongodb/src/cmap/connection.ts:740:20)
    at MessageStream.emit (events.js:315:20)
    at MessageStream.EventEmitter.emit (domain.js:486:12)
    at processIncomingData (/home/rico/DEV/ME/boilerplates/mercurius-connector-kit-mongoose/backend/node_modules/mongodb/src/cmap/message_stream.ts:167:12)
    at MessageStream._write (/home/rico/DEV/ME/boilerplates/mercurius-connector-kit-mongoose/backend/node_modules/mongodb/src/cmap/message_stream.ts:64:5)
    at writeOrBuffer (_stream_writable.js:352:12)
    at MessageStream.Writable.write (_stream_writable.js:303:10)
    at Socket.ondata (_stream_readable.js:719:22)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
(node:29600) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:29600) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:29600) UnhandledPromiseRejectionWarning: Error: findAndModify: support for field "fields" with value &{map[] [] false 0} is not implemented yet
    at MongoServerError.<anonymous> (/home/rico/DEV/ME/boilerplates/mercurius-connector-kit-mongoose/backend/node_modules/@babel/node/node_modules/core-js/internals/wrap-error-constructor-with-cause.js:37:62)
    at new Error (/home/rico/DEV/ME/boilerplates/mercurius-connector-kit-mongoose/backend/node_modules/@babel/node/node_modules/core-js/modules/es.error.cause.js:28:43)
    at new MongoError (/home/rico/DEV/ME/boilerplates/mercurius-connector-kit-mongoose/backend/node_modules/mongodb/src/error.ts:93:7)
    at new MongoServerError (/home/rico/DEV/ME/boilerplates/mercurius-connector-kit-mongoose/backend/node_modules/mongodb/src/error.ts:147:5)
    at MessageStream.messageHandler (/home/rico/DEV/ME/boilerplates/mercurius-connector-kit-mongoose/backend/node_modules/mongodb/src/cmap/connection.ts:740:20)
    at MessageStream.emit (events.js:315:20)
    at MessageStream.EventEmitter.emit (domain.js:486:12)
    at processIncomingData (/home/rico/DEV/ME/boilerplates/mercurius-connector-kit-mongoose/backend/node_modules/mongodb/src/cmap/message_stream.ts:167:12)
    at MessageStream._write (/home/rico/DEV/ME/boilerplates/mercurius-connector-kit-mongoose/backend/node_modules/mongodb/src/cmap/message_stream.ts:64:5)
    at writeOrBuffer (_stream_writable.js:352:12)
    at MessageStream.Writable.write (_stream_writable.js:303:10)
    at Socket.ondata (_stream_readable.js:719:22)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
(node:29600) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:29600) UnhandledPromiseRejectionWarning: Error: findAndModify: support for field "fields" with value &{map[] [] false 0} is not implemented yet
    at MongoServerError.<anonymous> (/home/rico/DEV/ME/boilerplates/mercurius-connector-kit-mongoose/backend/node_modules/@babel/node/node_modules/core-js/internals/wrap-error-constructor-with-cause.js:37:62)
    at new Error (/home/rico/DEV/ME/boilerplates/mercurius-connector-kit-mongoose/backend/node_modules/@babel/node/node_modules/core-js/modules/es.error.cause.js:28:43)
    at new MongoError (/home/rico/DEV/ME/boilerplates/mercurius-connector-kit-mongoose/backend/node_modules/mongodb/src/error.ts:93:7)
    at new MongoServerError (/home/rico/DEV/ME/boilerplates/mercurius-connector-kit-mongoose/backend/node_modules/mongodb/src/error.ts:147:5)
    at MessageStream.messageHandler (/home/rico/DEV/ME/boilerplates/mercurius-connector-kit-mongoose/backend/node_modules/mongodb/src/cmap/connection.ts:740:20)
    at MessageStream.emit (events.js:315:20)
    at MessageStream.EventEmitter.emit (domain.js:486:12)
    at processIncomingData (/home/rico/DEV/ME/boilerplates/mercurius-connector-kit-mongoose/backend/node_modules/mongodb/src/cmap/message_stream.ts:167:12)
    at MessageStream._write (/home/rico/DEV/ME/boilerplates/mercurius-connector-kit-mongoose/backend/node_modules/mongodb/src/cmap/message_stream.ts:64:5)
    at writeOrBuffer (_stream_writable.js:352:12)
    at MessageStream.Writable.write (_stream_writable.js:303:10)
    at Socket.ondata (_stream_readable.js:719:22)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
(node:29600) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```
Adding `useFindAndModify: false` to the connection options does not fix the problem either. For instance I get the error `(node:37288) UnhandledPromiseRejectionWarning: Error: option usefindandmodify is not supported`

Any idea on what could it be?

### Backend

PostresSQL in a docker container (latest)

### Environment

OS: Ubuntu 22.04 x86_64
Deployment: Docker using ghcr.io/ferretdb/ferretdb:1.15.0 image
Deployment details: Docker version 24.0.7

### What did you do?

```
await UserCollection.findOneAndUpdate(
        {
          username: user.username,
        },
        {
          ...user,
        },
        { upsert: true, new: true },
      );
```

### What did you expect to see?

No errors

### What did you see instead?

```
2023-12-01T08:38:20.838Z	WARN	// 172.17.0.1:44714 -> 172.17.0.3:27017 	clientconn/conn.go:603	Response message:
{
  "Checksum": 0,
  "FlagBits": 0,
  "Sections": [
    {
      "Document": {
        "$k": [
          "ok",
          "errmsg",
          "code",
          "codeName"
        ],
        "ok": {
          "$f": 0
        },
        "errmsg": "findAndModify: support for field \"fields\" with value \u0026{map[] [] false 0} is not implemented yet",
        "code": 238,
        "codeName": "NotImplemented"
      },
      "Kind": 0
    }
  ]
}



2023-12-01T08:38:20.841Z	INFO	postgresql	tracelog/tracelog.go:335	Query	{"sql": "UPDATE \"ferretdb\".\"_ferretdb_database_metadata\" SET _jsonb = $1 WHERE _jsonb->'_id' = $2", "args": ["{\"$s\":{\"p\":{\"_id\":{\"t\":\"string\"},\"table\":{\"t\":\"string\"},\"indexes (truncated 1465 bytes)","225573657222"], "time": "2.971537ms", "commandTag": "UPDATE 1", "pid": 310}
2023-12-01T08:38:20.844Z	INFO	postgresql	tracelog/tracelog.go:335	Query	{"sql": "UPDATE \"ferretdb\".\"_ferretdb_database_metadata\" SET _jsonb = $1 WHERE _jsonb->'_id' = $2", "args": ["{\"$s\":{\"p\":{\"_id\":{\"t\":\"string\"},\"table\":{\"t\":\"string\"},\"indexes (truncated 1465 bytes)","225573657222"], "time": "1.494837ms", "commandTag": "UPDATE 1", "pid": 310}
2023-12-01T08:38:20.847Z	INFO	postgresql	tracelog/tracelog.go:335	Query	{"pid": 310, "sql": "UPDATE \"ferretdb\".\"_ferretdb_database_metadata\" SET _jsonb = $1 WHERE _jsonb->'_id' = $2", "args": ["{\"$s\":{\"p\":{\"_id\":{\"t\":\"string\"},\"table\":{\"t\":\"string\"},\"indexes (truncated 1465 bytes)","225573657222"], "time": "1.53699ms", "commandTag": "UPDATE 1"}
```

**Comment by AlekSi** [comment]
Please try with packages from https://github.com/FerretDB/FerretDB/actions/runs/7057897707?pr=3798

**Comment by ecerroni** [comment]
That fixed it :+1: 

Thank you very much!

**Comment by AlekSi** [comment]
It is now supported by FerretDB v2: https://github.com/FerretDB/FerretDB/releases/tag/v2.0.0-rc.1
