### ISSUE TITLE
`sort` crashes FerretDB

### ISSUE THREAD

**Issue by ribaraka** [FerretDB/FerretDB#422]
When I sent a query `db.values.find({value: 42}).sort({value : 1})` I got an error:
```
INFO	pg.Pool	v4@v4.15.0/conn.go:355	Query	{"sql": "SELECT _jsonb FROM \"values\".\"values\"", "args": [], "time": "24.831158ms", "rowCount": 42, "pid": 646}
clientconn/conn.go:114	unhandled type *types.Array
(err = <nil>)
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run.func1
	github.com/FerretDB/FerretDB/internal/clientconn/conn.go:114
runtime.gopanic
	runtime/panic.go:844
github.com/FerretDB/FerretDB/internal/handlers/common.compareScalars
	github.com/FerretDB/FerretDB/internal/handlers/common/compare.go:176
github.com/FerretDB/FerretDB/internal/handlers/common.lessFunc.func1
	github.com/FerretDB/FerretDB/internal/handlers/common/sort.go:76
github.com/FerretDB/FerretDB/internal/handlers/common.(*docsSorter).Less
	github.com/FerretDB/FerretDB/internal/handlers/common/sort.go:139
sort.insertionSort
	sort/sort.go:40
sort.quickSort
	sort/sort.go:222
sort.Sort
	sort/sort.go:231
github.com/FerretDB/FerretDB/internal/handlers/common.(*docsSorter).Sort
	github.com/FerretDB/FerretDB/internal/handlers/common/sort.go:110
github.com/FerretDB/FerretDB/internal/handlers/common.SortDocuments
	github.com/FerretDB/FerretDB/internal/handlers/common/sort.go:57
github.com/FerretDB/FerretDB/internal/handlers/pg.(*Handler).MsgFind
	github.com/FerretDB/FerretDB/internal/handlers/pg/msg_find.go:108
github.com/FerretDB/FerretDB/internal/handlers/pg.(*Handler).handleOpMsg
	github.com/FerretDB/FerretDB/internal/handlers/pg/handler.go:208
github.com/FerretDB/FerretDB/internal/handlers/pg.(*Handler).Handle
	github.com/FerretDB/FerretDB/internal/handlers/pg/handler.go:104
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run
	github.com/FerretDB/FerretDB/internal/clientconn/conn.go:167
github.com/FerretDB/FerretDB/internal/clientconn.(*Listener).Run.func2
	github.com/FerretDB/FerretDB/internal/clientconn/listener.go:135
panic: unhandled type *types.Array [recovered]
	panic: unhandled type *types.Array
(err = <nil>)

goroutine 10 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0000fe300, {0x0, 0x0, 0x0})
	go.uber.org/zap@v1.21.0/zapcore/entry.go:232 +0x60a
go.uber.org/zap.(*SugaredLogger).log(0xc0000b6288, 0x3, {0xe86a91, 0xd}, {0xc00035a910, 0x2, 0x2}, {0x0, 0x0, 0x0})
	go.uber.org/zap@v1.21.0/sugar.go:227 +0x13b
go.uber.org/zap.(*SugaredLogger).DPanicf(...)
	go.uber.org/zap@v1.21.0/sugar.go:154
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run.func1()
	github.com/FerretDB/FerretDB/internal/clientconn/conn.go:114 +0x1ab
panic({0xdae240, 0xc0004e3830})
	runtime/panic.go:844 +0x258
github.com/FerretDB/FerretDB/internal/handlers/common.compareScalars({0xe26200, 0xc0004be180?}, {0xe26200?, 0xc0000cbcf8?})
	github.com/FerretDB/FerretDB/internal/handlers/common/compare.go:176 +0x17ed
github.com/FerretDB/FerretDB/internal/handlers/common.lessFunc.func1(0x0?, 0x8?)
	github.com/FerretDB/FerretDB/internal/handlers/common/sort.go:76 +0xe5
github.com/FerretDB/FerretDB/internal/handlers/common.(*docsSorter).Less(0xc000503500, 0x1, 0x0)
	github.com/FerretDB/FerretDB/internal/handlers/common/sort.go:139 +0x274
sort.insertionSort({0xfb19c0, 0xc000503500}, 0x0, 0x4)
	sort/sort.go:40 +0xd1
sort.quickSort({0xfb19c0, 0xc000503500}, 0x0, 0x4, 0x6)
	sort/sort.go:222 +0x1d5
sort.Sort({0xfb19c0, 0xc000503500})
	sort/sort.go:231 +0x65
github.com/FerretDB/FerretDB/internal/handlers/common.(*docsSorter).Sort(0xc000503500, {0xc000169f00, 0x4, 0x10})
	github.com/FerretDB/FerretDB/internal/handlers/common/sort.go:110 +0x96
github.com/FerretDB/FerretDB/internal/handlers/common.SortDocuments({0xc000169f00?, 0x4, 0x10}, 0xc0001cd79a?)
	github.com/FerretDB/FerretDB/internal/handlers/common/sort.go:57 +0x2a8
github.com/FerretDB/FerretDB/internal/handlers/pg.(*Handler).MsgFind(0xc0000dcc80, {0xfb4348, 0xc0000a3080}, 0x4?)
	github.com/FerretDB/FerretDB/internal/handlers/pg/msg_find.go:108 +0xa74
github.com/FerretDB/FerretDB/internal/handlers/pg.(*Handler).handleOpMsg(0xc0000b98c0?, {0xfb4348, 0xc0000a3080}, 0x1?, {0xc0001cd5dc, 0x4})
	github.com/FerretDB/FerretDB/internal/handlers/pg/handler.go:208 +0x242
github.com/FerretDB/FerretDB/internal/handlers/pg.(*Handler).Handle(0xc0000dcc80, {0xfb4348, 0xc0000a3080}, 0xc0001cd560, {0xfb4c80?, 0xc0000f9160?})
	github.com/FerretDB/FerretDB/internal/handlers/pg/handler.go:104 +0x7ce
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run(0xc0000a3040, {0xfb4348?, 0xc0000a3080})
	github.com/FerretDB/FerretDB/internal/clientconn/conn.go:167 +0xa85
github.com/FerretDB/FerretDB/internal/clientconn.(*Listener).Run.func2()
	github.com/FerretDB/FerretDB/internal/clientconn/listener.go:135 +0x63f
created by github.com/FerretDB/FerretDB/internal/clientconn.(*Listener).Run
	github.com/FerretDB/FerretDB/internal/clientconn/listener.go:105 +0x72b
task: Failed to run task "run": exit status 2
```

**Comment by AlekSi** [comment]
Moved the feature aspect to #423.
