### ISSUE TITLE
Competing tasks `env-setup` and `env-up`

### ISSUE THREAD

**Issue by rumyantseva** [FerretDB/FerretDB#647]
This is quite a corner case, but maybe there is a simple solution to fix it.

1. I run `task env-setup`. It works as expected, with no errors happening. The process keeps running.
2. In a separate tab I run `task env-up`. It panics:
```
panic: listen tcp 127.0.0.1:8089: bind: address already in use

goroutine 10 [running]:
github.com/FerretDB/FerretDB/internal/util/debug.RunHandler.func2()
	/Users/elena/ferret/FerretDB/internal/util/debug/debug.go:56 +0x16c
created by github.com/FerretDB/FerretDB/internal/util/debug.RunHandler
	/Users/elena/ferret/FerretDB/internal/util/debug/debug.go:53 +0x27c
exit status 2
task: Failed to run task "env-setup": exit status 1
```
4. In the meantime, with no additional actions, the running `env-setup` process stops too! Here are the logs:
```
$ task env-setup
task: [gen-version] go generate -x ./internal/util/version
go run ./generate.go
task: [env-setup] go run ./cmd/envtool/main.go
2022-05-26T15:20:36.636+0200	INFO	envtool/main.go:338	Waiting for port 5432 to be up...
2022-05-26T15:20:36.636+0200	INFO	debug	debug/debug.go:59	Starting debug server on http://127.0.0.1:8089/
2022-05-26T15:20:36.636+0200	INFO	envtool/main.go:330	Waiting for port 37017 to be up...
2022-05-26T15:21:11.741+0200	INFO	postgres.monila_and_values	envtool/main.go:167	Importing databases...
2022-05-26T15:21:11.741+0200	INFO	mongodb	envtool/main.go:129	Importing database...
2022-05-26T15:21:11.743+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:76	Listening on 127.0.0.1:27018 ...
2022-05-26T19:06:12.727+0545	connected to: mongodb://127.0.0.1:27017/monila
2022-05-26T19:06:12.727+0545	dropping: monila.staff
2022-05-26T19:06:12.773+0545	2 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T19:06:12.885+0545	connected to: mongodb://host.docker.internal:27018/monila
2022-05-26T19:06:12.899+0545	dropping: monila.store
2022-05-26T15:21:12.927+0200	INFO	pg/msg_insert.go:67	Created table.	{"schema": "monila", "table": "store"}
2022-05-26T15:21:12.931+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T15:21:12.931+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T19:06:12.931+0545	2 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T15:21:12.937+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T19:06:12.952+0545	connected to: mongodb://host.docker.internal:27018/monila
2022-05-26T19:06:12.953+0545	dropping: monila.film_category
2022-05-26T15:21:12.977+0200	INFO	pg/msg_insert.go:67	Created table.	{"schema": "monila", "table": "film_category"}
2022-05-26T19:06:13.012+0545	connected to: mongodb://host.docker.internal:27018/monila
2022-05-26T19:06:13.013+0545	dropping: monila.actor
2022-05-26T15:21:13.035+0200	INFO	pg/msg_insert.go:67	Created table.	{"schema": "monila", "table": "actor"}
2022-05-26T19:06:13.042+0545	connected to: mongodb://127.0.0.1:27017/values
2022-05-26T19:06:13.042+0545	dropping: values.values
2022-05-26T19:06:13.057+0545	42 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T19:06:13.100+0545	connected to: mongodb://host.docker.internal:27018/monila
2022-05-26T19:06:13.101+0545	dropping: monila.address
2022-05-26T15:21:13.144+0200	INFO	pg/msg_insert.go:67	Created table.	{"schema": "monila", "table": "address"}
2022-05-26T19:06:13.146+0545	connected to: mongodb://host.docker.internal:27018/monila
2022-05-26T19:06:13.147+0545	dropping: monila.film_actor
2022-05-26T19:06:13.179+0545	connected to: mongodb://127.0.0.1:27017/monila
2022-05-26T19:06:13.179+0545	dropping: monila.store
2022-05-26T15:21:13.205+0200	INFO	pg/msg_insert.go:67	Created table.	{"schema": "monila", "table": "film_actor"}
2022-05-26T19:06:13.206+0545	2 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T19:06:13.241+0545	connected to: mongodb://host.docker.internal:27018/monila
2022-05-26T19:06:13.243+0545	dropping: monila.category
2022-05-26T15:21:13.258+0200	INFO	pg/msg_insert.go:67	Created table.	{"schema": "monila", "table": "category"}
2022-05-26T19:06:13.293+0545	connected to: mongodb://host.docker.internal:27018/monila
2022-05-26T19:06:13.295+0545	dropping: monila.rental
2022-05-26T15:21:13.307+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T15:21:13.307+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T15:21:13.307+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T19:06:13.307+0545	16 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T19:06:13.335+0545	connected to: mongodb://host.docker.internal:27018/monila
2022-05-26T19:06:13.339+0545	dropping: monila.city
2022-05-26T15:21:13.368+0200	INFO	pg/msg_insert.go:67	Created table.	{"schema": "monila", "table": "rental"}
2022-05-26T19:06:13.394+0545	connected to: mongodb://127.0.0.1:27017/monila
2022-05-26T19:06:13.395+0545	dropping: monila.category
2022-05-26T15:21:13.398+0200	INFO	pg/msg_insert.go:67	Created table.	{"schema": "monila", "table": "city"}
2022-05-26T19:06:13.422+0545	16 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T19:06:13.451+0545	connected to: mongodb://127.0.0.1:27017/monila
2022-05-26T19:06:13.451+0545	dropping: monila.film_actor
2022-05-26T15:21:13.488+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T15:21:13.488+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T19:06:13.487+0545	200 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T15:21:13.496+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T19:06:13.505+0545	connected to: mongodb://127.0.0.1:27017/monila
2022-05-26T19:06:13.505+0545	dropping: monila.film
2022-05-26T19:06:13.557+0545	connected to: mongodb://host.docker.internal:27018/monila
2022-05-26T19:06:13.560+0545	dropping: monila.customer
2022-05-26T19:06:13.625+0545	connected to: mongodb://host.docker.internal:27018/monila
2022-05-26T19:06:13.627+0545	dropping: monila.staff
2022-05-26T15:21:13.640+0200	INFO	pg/msg_insert.go:67	Created table.	{"schema": "monila", "table": "customer"}
2022-05-26T15:21:13.653+0200	INFO	pg/msg_insert.go:67	Created table.	{"schema": "monila", "table": "staff"}
2022-05-26T19:06:13.659+0545	connected to: mongodb://127.0.0.1:27017/monila
2022-05-26T19:06:13.659+0545	dropping: monila.country
2022-05-26T15:21:13.661+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T15:21:13.661+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T15:21:13.661+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T19:06:13.661+0545	2 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T19:06:13.667+0545	5462 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T19:06:13.674+0545	1000 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T19:06:13.688+0545	109 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T19:06:13.709+0545	connected to: mongodb://host.docker.internal:27018/monila
2022-05-26T19:06:13.712+0545	dropping: monila.language
2022-05-26T15:21:13.721+0200	INFO	pg/msg_insert.go:67	Created table.	{"schema": "monila", "table": "language"}
2022-05-26T15:21:13.734+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T15:21:13.734+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T19:06:13.733+0545	6 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T15:21:13.737+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T19:06:13.759+0545	connected to: mongodb://127.0.0.1:27017/monila
2022-05-26T19:06:13.759+0545	dropping: monila.language
2022-05-26T19:06:13.784+0545	6 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T19:06:13.816+0545	connected to: mongodb://host.docker.internal:27018/values
2022-05-26T19:06:13.820+0545	dropping: values.values
2022-05-26T15:21:13.831+0200	INFO	pg/msg_insert.go:67	Created table.	{"schema": "values", "table": "values"}
2022-05-26T19:06:13.849+0545	connected to: mongodb://host.docker.internal:27018/monila
2022-05-26T19:06:13.855+0545	dropping: monila.film
2022-05-26T19:06:13.899+0545	connected to: mongodb://host.docker.internal:27018/monila
2022-05-26T19:06:13.904+0545	dropping: monila.country
2022-05-26T15:21:13.931+0200	INFO	pg/msg_insert.go:67	Created table.	{"schema": "monila", "table": "country"}
2022-05-26T19:06:13.960+0545	connected to: mongodb://127.0.0.1:27017/monila
2022-05-26T19:06:13.961+0545	dropping: monila.film_category
2022-05-26T15:21:13.982+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T15:21:13.982+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T19:06:13.982+0545	42 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T15:21:13.984+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T15:21:13.987+0200	INFO	pg/msg_insert.go:67	Created table.	{"schema": "monila", "table": "film"}
2022-05-26T19:06:14.010+0545	connected to: mongodb://127.0.0.1:27017/monila
2022-05-26T19:06:14.011+0545	dropping: monila.rental
2022-05-26T19:06:14.016+0545	1000 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T19:06:14.078+0545	connected to: mongodb://127.0.0.1:27017/monila
2022-05-26T19:06:14.079+0545	dropping: monila.address
2022-05-26T19:06:14.136+0545	603 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T19:06:14.195+0545	connected to: mongodb://127.0.0.1:27017/monila
2022-05-26T19:06:14.195+0545	dropping: monila.customer
2022-05-26T19:06:14.219+0545	connected to: mongodb://127.0.0.1:27017/monila
2022-05-26T19:06:14.219+0545	dropping: monila.inventory
2022-05-26T19:06:14.274+0545	connected to: mongodb://127.0.0.1:27017/monila
2022-05-26T19:06:14.274+0545	dropping: monila.city
2022-05-26T19:06:14.275+0545	599 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T19:06:14.319+0545	600 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T19:06:14.329+0545	connected to: mongodb://host.docker.internal:27018/monila
2022-05-26T19:06:14.336+0545	dropping: monila.inventory
2022-05-26T15:21:14.350+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T19:06:14.350+0545	109 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T15:21:14.351+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T15:21:14.354+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T15:21:14.385+0200	INFO	pg/msg_insert.go:67	Created table.	{"schema": "monila", "table": "inventory"}
2022-05-26T19:06:14.496+0545	connected to: mongodb://127.0.0.1:27017/monila
2022-05-26T19:06:14.496+0545	dropping: monila.actor
2022-05-26T19:06:14.513+0545	4581 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T19:06:14.531+0545	200 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T15:21:14.886+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T15:21:14.886+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T15:21:14.886+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T19:06:14.886+0545	603 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T19:06:14.963+0545	16044 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T15:21:14.979+0200	INFO	mongodb	envtool/main.go:160	Done in 3.237882083s.
2022-05-26T15:21:15.041+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T19:06:15.041+0545	600 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T15:21:15.042+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T15:21:15.044+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T15:21:15.180+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T19:06:15.180+0545	599 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T15:21:15.180+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T15:21:15.180+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T15:21:15.345+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T15:21:15.345+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T15:21:15.345+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T19:06:15.345+0545	1000 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T15:21:15.865+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T15:21:15.865+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T19:06:15.865+0545	1000 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T15:21:15.867+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T19:06:16.147+0545	[#########...............] monila.film_actor	325KB/866KB (37.6%)
2022-05-26T19:06:16.294+0545	[###.....................] monila.rental	696KB/5.32MB (12.8%)
2022-05-26T19:06:17.331+0545	[################........] monila.inventory	589KB/884KB (66.7%)
2022-05-26T19:06:19.147+0545	[######################..] monila.film_actor	801KB/866KB (92.5%)
2022-05-26T19:06:19.295+0545	[#######.................] monila.rental	1.67MB/5.32MB (31.5%)
2022-05-26T19:06:20.300+0545	[########################] monila.inventory	884KB/884KB (100.0%)
2022-05-26T15:21:20.301+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T15:21:20.301+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T19:06:20.301+0545	4581 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T15:21:20.303+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T15:21:20.920+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T15:21:20.920+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T15:21:20.920+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T19:06:20.920+0545	[########################] monila.film_actor	866KB/866KB (100.0%)
2022-05-26T19:06:20.920+0545	5462 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T19:06:22.294+0545	[############............] monila.rental	2.67MB/5.32MB (50.2%)
2022-05-26T19:06:25.294+0545	[###############.........] monila.rental	3.33MB/5.32MB (62.7%)
2022-05-26T19:06:28.294+0545	[#####################...] monila.rental	4.66MB/5.32MB (87.6%)
2022-05-26T15:21:30.260+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T15:21:30.261+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T19:06:30.260+0545	[########################] monila.rental	5.32MB/5.32MB (100.0%)
2022-05-26T19:06:30.260+0545	16044 document(s) imported successfully. 0 document(s) failed to import.
2022-05-26T15:21:30.262+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:141	Connection stopped
2022-05-26T15:21:30.275+0200	INFO	postgres.monila_and_values.listener	clientconn/listener.go:148	Waiting for all connections to stop...
2022-05-26T15:21:30.275+0200	INFO	postgres.monila_and_values	envtool/main.go:224	Done in 18.533826791s.
2022-05-26T15:21:30.551+0200	INFO	envtool/main.go:391	Done.
```
5. Now when I run `task env-setup` again, it fails:
```
$ task env-setup
task: [gen-version] go generate -x ./internal/util/version
go run ./generate.go
task: [env-setup] go run ./cmd/envtool/main.go
2022-05-26T15:27:19.812+0200	INFO	envtool/main.go:330	Waiting for port 37017 to be up...
2022-05-26T15:27:19.812+0200	INFO	envtool/main.go:338	Waiting for port 5432 to be up...
2022-05-26T15:27:19.813+0200	INFO	debug	debug/debug.go:59	Starting debug server on http://127.0.0.1:8089/
Looks like something went wrong..
Please file an issue with all that information below:

	OS: darwin
	Arch: arm64
	Version: v0.2.1-8-g3eddbf1-dirty
	Commit: 3eddbf126ee5ce9eeccd195ff65f6894b3bc7652
	Branch: main

	Go version: go1.18.2
	git version 2.32.1 (Apple Git-133)
	Docker Compose version v2.5.1
	git version 2.32.1 (Apple Git-133)

	Error: schema or table already exist
exit status 2
task: Failed to run task "env-setup": exit status 1
```
6. I run `task env-down` and then `task env-setup`, and everything works again.

**Comment by AlekSi** [comment]
> I run `task env-setup`

Ok, why? That internal target is not documented anywhere. We don't expect contributors to run it.

**Comment by rumyantseva** [comment]
@AlekSi well, I'm not sure why I tried `env-setup`... From the `Taskfile` it looked reasonable to me what this task was doing :)

**Comment by AlekSi** [comment]
It doesn't have `desc`ription, is not visible in `task -l` output, and is not mentioned in the [CONTRIBUTING.md](https://github.com/FerretDB/FerretDB/blob/main/CONTRIBUTING.md#setting-up-the-development-environment). So I'm not sure what we can do there.

Maybe add `-internal` suffix to all internal targets? Does not look nice to me.

**Comment by rumyantseva** [comment]
I think it's fine to just close this issue and do nothing.
