### ISSUE TITLE
`proxy.(*Router).Route` panics

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#947]
f1f559a77bcb8c101ee6ed3a942c8ba179088910 panics on `db.runCommand({explain: {count: "values"}})` in `task mongosh` with:

```
2022-07-26T21:21:08.947+0300	DPANIC	// 127.0.0.1:49325 -> 127.0.0.1:27017 	clientconn/conn.go:130	expected length 70 (marshaled body size) + 16 (fixed marshaled header size) = 86, got 72
(err = <nil>)
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run.func2
	github.com/FerretDB/FerretDB/internal/clientconn/conn.go:130
runtime.gopanic
	runtime/panic.go:844
github.com/FerretDB/FerretDB/internal/wire.WriteMessage
	github.com/FerretDB/FerretDB/internal/wire/msg_body.go:106
github.com/FerretDB/FerretDB/internal/handlers/proxy.(*Router).Route
	github.com/FerretDB/FerretDB/internal/handlers/proxy/proxy.go:57
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run
	github.com/FerretDB/FerretDB/internal/clientconn/conn.go:188
github.com/FerretDB/FerretDB/internal/clientconn.(*Listener).Run.func2
	github.com/FerretDB/FerretDB/internal/clientconn/listener.go:149
panic: expected length 70 (marshaled body size) + 16 (fixed marshaled header size) = 86, got 72 [recovered]
	panic: expected length 70 (marshaled body size) + 16 (fixed marshaled header size) = 86, got 72
(err = <nil>)

goroutine 50 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0000ce840, {0x0, 0x0, 0x0})
	go.uber.org/zap@v1.21.0/zapcore/entry.go:232 +0x44c
go.uber.org/zap.(*SugaredLogger).log(0xc0000100d0, 0x3, {0x10540d9f4, 0xd}, {0xc0006c32e8, 0x2, 0x2}, {0x0, 0x0, 0x0})
	go.uber.org/zap@v1.21.0/sugar.go:227 +0x110
go.uber.org/zap.(*SugaredLogger).DPanicf(...)
	go.uber.org/zap@v1.21.0/sugar.go:154
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run.func2()
	github.com/FerretDB/FerretDB/internal/clientconn/conn.go:130 +0x134
panic({0x10565ac40, 0xc000193c30})
	runtime/panic.go:844 +0x258
github.com/FerretDB/FerretDB/internal/wire.WriteMessage(0xc0000100b8?, 0xc000701530, {0x1057d6e20, 0xc0001ded00})
	github.com/FerretDB/FerretDB/internal/wire/msg_body.go:106 +0x28c
github.com/FerretDB/FerretDB/internal/handlers/proxy.(*Router).Route(0xc00009a3c0, {0x1057d64b0, 0xc00043c9c0}, 0xc000701710?, {0x1057d6e20, 0xc0001ded00})
	github.com/FerretDB/FerretDB/internal/handlers/proxy/proxy.go:57 +0xc4
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run(0xc000050050, {0x1057d64b0?, 0xc00043c9c0})
	github.com/FerretDB/FerretDB/internal/clientconn/conn.go:188 +0x8ec
github.com/FerretDB/FerretDB/internal/clientconn.(*Listener).Run.func2()
	github.com/FerretDB/FerretDB/internal/clientconn/listener.go:149 +0x994
created by github.com/FerretDB/FerretDB/internal/clientconn.(*Listener).Run
	github.com/FerretDB/FerretDB/internal/clientconn/listener.go:107 +0x5f0
```

That seems to be due to this code copying `"$db"` field.

**Comment by noisersup** [comment]
A similar issue after running `db.values.findAndModify({query:{"_id":"string"}, update: {"v":"test"}})` in mongosh:
```
2022-07-28T16:23:14.715+0200    DPANIC  // 172.19.0.3:51560 -> 172.17.0.1:27017         clientconn/conn.go:130  expected length 143 (marshaled body size) + 16 (fixed marshaled header size) = 159, got 143
(err = <nil>)
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run.func2
        github.com/FerretDB/FerretDB/internal/clientconn/conn.go:130
runtime.gopanic
        runtime/panic.go:844
github.com/FerretDB/FerretDB/internal/wire.WriteMessage
        github.com/FerretDB/FerretDB/internal/wire/msg_body.go:106
github.com/FerretDB/FerretDB/internal/handlers/proxy.(*Router).Route
        github.com/FerretDB/FerretDB/internal/handlers/proxy/proxy.go:57
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run
        github.com/FerretDB/FerretDB/internal/clientconn/conn.go:188
github.com/FerretDB/FerretDB/internal/clientconn.(*Listener).Run.func2
        github.com/FerretDB/FerretDB/internal/clientconn/listener.go:149
panic: expected length 143 (marshaled body size) + 16 (fixed marshaled header size) = 159, got 143 [recovered]
        panic: expected length 143 (marshaled body size) + 16 (fixed marshaled header size) = 159, got 143
(err = <nil>)

goroutine 30 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000156180, {0x0, 0x0, 0x0})
        go.uber.org/zap@v1.21.0/zapcore/entry.go:232 +0x60a
go.uber.org/zap.(*SugaredLogger).log(0xc0000101a8, 0x3, {0x1436133, 0xd}, {0xc0001872f8, 0x2, 0x2}, {0x0, 0x0, 0x0})
        go.uber.org/zap@v1.21.0/sugar.go:227 +0x13b
go.uber.org/zap.(*SugaredLogger).DPanicf(...)
        go.uber.org/zap@v1.21.0/sugar.go:154
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run.func2()
        github.com/FerretDB/FerretDB/internal/clientconn/conn.go:130 +0x1ab
panic({0x12c2b60, 0xc000514600})
        runtime/panic.go:844 +0x258
github.com/FerretDB/FerretDB/internal/wire.WriteMessage(0xc0000101a0?, 0xc0006139f0, {0x15fc530, 0xc0003b8e20})
        github.com/FerretDB/FerretDB/internal/wire/msg_body.go:106 +0x36a
github.com/FerretDB/FerretDB/internal/handlers/proxy.(*Router).Route(0xc0003b83a0, {0x15fbb88, 0xc000610ed0}, 0xc000613e60?, {0x15fc530, 0xc0003b8e20})
        github.com/FerretDB/FerretDB/internal/handlers/proxy/proxy.go:57 +0x116
github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run(0xc0003fc000, {0x15fbb88?, 0xc000610ed0})
        github.com/FerretDB/FerretDB/internal/clientconn/conn.go:188 +0xc3f
github.com/FerretDB/FerretDB/internal/clientconn.(*Listener).Run.func2()
        github.com/FerretDB/FerretDB/internal/clientconn/listener.go:149 +0xd25
created by github.com/FerretDB/FerretDB/internal/clientconn.(*Listener).Run
        github.com/FerretDB/FerretDB/internal/clientconn/listener.go:107 +0x785
task: Failed to run task "run": exit status 2
```

**Comment by AlekSi** [comment]
Fixed some time ago
